Improve output with invalid asyncio_mode
Instead of a long INTERNALERROR> stack trace, output a proper error
message:

    $ pytest -o asyncio_mode=True
    =================== test session starts ====================
    platform linux -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
    ERROR: 'True' is not a valid asyncio_mode. Valid modes: auto, strict.

See https://github.com/pytest-dev/pytest/issues/11083